[tool.poetry]
name = "nornir_srl"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
nornir = "^3.3.0"
nornir-utils = "^0.2.0"
pygnmi = "^0.8.9"
nornir-jinja2 = "^0.2.0"
nornir-scrapli = "^2022.1.30"
GitPython = "^3.1.29"
rich = "^12.6.0"
natsort = "^8.2.0"
pydantic = "^1.10.2"
deepdiff = "^6.2.1"

[tool.poetry.plugins."nornir.plugins.connections"]
"srlinux" = "nornir_srl.connections.srlinux:SrLinux"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
notebook = "^6.4.11"
bpython = "^0.22.1"
blessings = "^1.7"
pandas = "^1.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
