clab-4l2s-l1:
    hostname: clab-4l2s-l1
    groups: [srl, leafs]
    username: admin
    password: admin
    port: 57400
    platform: ixr-d2

clab-4l2s-l2:
    hostname: clab-4l2s-l2
    groups: [srl, leafs]
    username: admin
    password: admin
    port: 57400
    platform: ixr-d2
