clab-4l2s-l1:
  interfaces:
    - name: ethernet-1/48
      description: blah
      admin_state: enable
      subinterface:
        admin_state: enable
        ipv4_address: 192.168.5.1/31
clab-4l2s-l2:
  interfaces:
    - name: system0
      description: blah
      admin_state: enable
      subinterface:
        admin_state: enable
        ipv4_address: 192.168.255.1/32

    
  