clab-4l2s-l1:
    hostname: clab-4l2s-l1
    groups: [srl, fabric, leafs]
    username: admin
    password: NokiaSrl1!
    port: 57400
    platform: ixr-d2
    data:
        router_id: 192.168.255.1
        side: A
        leafpair: P1
        isl:
            ethernet-1/48:
                ipv4_address: 192.168.0.1/31
            ethernet-1/49:
                ipv4_address: 192.168.0.3/31

clab-4l2s-l2:
    hostname: clab-4l2s-l2
    groups: [srl, fabric, leafs]
    username: admin
    password: NokiaSrl1!
    port: 57400
    platform: ixr-d2
    data:
        router_id: 192.168.255.2
        side: B
        leafpair: P1
        
clab-4l2s-l3:
    hostname: clab-4l2s-l3
    groups: [srl, fabric, leafs]
    username: admin
    password: NokiaSrl1!
    port: 57400
    platform: ixr-d2
    data:
        router_id: 192.168.255.3
        side: A
        leafpair: P2
        
clab-4l2s-l4:
    hostname: clab-4l2s-l4
    groups: [srl, fabric, leafs]
    username: admin
    password: NokiaSrl1!
    port: 57400
    platform: ixr-d2
    data:
        router_id: 192.168.255.4
        side: B
        leafpair: P2

clab-4l2s-s1:
    hostname: clab-4l2s-s1
    groups: [srl, fabric, spines]
    username: admin
    password: NokiaSrl1!
    port: 57400
    platform: ixr-d2
    data:
        router_id: 192.168.255.101
        side: A

clab-4l2s-s2:
    hostname: clab-4l2s-s2
    groups: [srl, fabric, spines]
    username: admin
    password: NokiaSrl1!
    port: 57400
    platform: ixr-d2
    data:
        router_id: 192.168.255.102
        side: B
#clab-4l2s-tor34:
#    hostname: clab-4l2s-tor34
#    username: admin
#    password: NokiaSrl1!
#    groups: [ srl ]
#    port: 57400
#    platform: ixr-d2
