clab-fcli_demo-l1:
    hostname: clab-fcli_demo-l1
    groups: [srl, fabric, leafs]
    username: admin
    password: NokiaSrl1!
    port: 57400
    platform: ixr-d2
    data:
        router_id: 192.168.255.1
        side: A
        leafpair: P1
        isl:
            ethernet-1/48:
                ipv4_address: 192.168.0.1/31
            ethernet-1/49:
                ipv4_address: 192.168.0.3/31

clab-fcli_demo-l2:
    hostname: clab-fcli_demo-l2
    groups: [srl, fabric, leafs]
    username: admin
    password: NokiaSrl1!
    port: 57400
    platform: ixr-d2
    data:
        router_id: 192.168.255.2
        side: B
        leafpair: P1
        
clab-fcli_demo-l3:
    hostname: clab-fcli_demo-l3
    groups: [srl, fabric, leafs]
    username: admin
    password: NokiaSrl1!
    port: 57400
    platform: ixr-d2
    data:
        router_id: 192.168.255.3
        side: A
        leafpair: P2
        
clab-fcli_demo-l4:
    hostname: clab-fcli_demo-l4
    groups: [srl, fabric, leafs]
    username: admin
    password: NokiaSrl1!
    port: 57400
    platform: ixr-d2
    data:
        router_id: 192.168.255.4
        side: B
        leafpair: P2

clab-fcli_demo-s1:
    hostname: clab-fcli_demo-s1
    groups: [srl, fabric, spines]
    username: admin
    password: NokiaSrl1!
    port: 57400
    platform: ixr-d2
    data:
        router_id: 192.168.255.101
        side: A

clab-fcli_demo-s2:
    hostname: clab-fcli_demo-s2
    groups: [srl, fabric, spines]
    username: admin
    password: NokiaSrl1!
    port: 57400
    platform: ixr-d2
    data:
        router_id: 192.168.255.102
        side: B
