---
inventory:
    #    plugin: SimpleInventory
    plugin: YAMLInventory
    options:
        host_file: "./hosts.yaml"
        group_file: "./groups.yaml"
        defaults_file: "./defaults.yaml"
runner:
    plugin: threaded
    options:
        num_workers: 20
    
