---
inventory:
    #    plugin: SimpleInventory
    plugin: YAMLInventory
    options:
        host_file: "/cfg/hosts.yaml"
        group_file: "/cfg/groups.yaml"
        defaults_file: "/cfg/defaults.yaml"
runner:
    plugin: threaded
    options:
        num_workers: 20
    
