clab-4l2s-l1:
  network_instance:
  - name: default
    admin_state: enable
    router_id: 192.168.255.1
    interfaces:
    - ethernet-1/48.0
    - ethernet-1/49.0
    - system0.0
clab-4l2s-l2:
  network_instance:
  - name: default
    admin_state: enable
    router_id: 192.168.255.2
    interfaces:
    - ethernet-1/48.0
    - ethernet-1/49.0
    - system0.0
